# Generated by Django 4.2.5 on 2023-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer',
            field=models.TextField(blank=True, null=True, verbose_name='有料会員'),
        ),
    ]
